# Config

# Data location
data:
  time0: /path/to/time0/folder
  time1: /path/to/time1/folder
  time3: /path/to/time3/folder
  time6: /path/to/time6/folder

# Paths to the comet executable, the comet params file, the database, and the percolator executable
# The Snakefile assumes riana can be executed in the shell by riana
paths:
  comet: /path/to/comet_source_2020013/comet.exe
  comet_params: /path/to/params/comet.params
  fasta: /path/tp/database.fas
  percolator: /path/to/percolator

# Integration and fitting parameters
params:
  model: simple     # fitting model (simple, guan, fornasiero)
  label_type: hw        # labeling type (aa or hw)
  isotopomers: 0,1,2,3,4,5   # isotopomer to integrate (0,1,2,3,4,5 for deuterium; 0,6 for heavy lysine)
  mass_tol: 15         # mass tolerance in ppm for integration (e.g., 25)
  ria_max: 1          # final precursor ria
  kp: 10              # guan model parameter (kp) or fornasiero model parameter (b)
  kr: 0.15              # fornasiero model parameter (a)
  rp: 5.52              # fornasiero model parameter (r)
  depth: 1             # minimum number of data points

# Number of threads
threads:
  comet: 8
  riana: 4
  fitcurve: 12