# Config

# Data location
data:
  time0: /path/to/time0.mzML.gz
  time1: /path/to/time1.mzML.gz
  time3: /path/to/time3.mzML.gz
  time6: /path/to/time6.mzML.gz

# Paths to the comet executable, the comet params file, the database, and the percolator executable
paths:
  comet: /path/to/comet_source_2020013/comet.exe
  comet_params: /path/to/params/comet.params
  fasta: /path/tp/database.fas
  percolator: /path/to/percolator

# Integratin and fitting parameters
params:
  label_type: aa    # labeling type (aa or hw)
  isotopomers: 0,6  # isotopomer to integrate (0,1,2,3,4,5 for deuterium; 0,6 for heavy lysine)
  ria_max: 0.42     # final precursor ria
  kp: 0.52          # guan model parameter (kp) or fornasiero model parameter (b)
  kr: 0.05          # fornasiero model parameter (a)
  rp: 10            # fornasiero model parameter (r)
  depth: 12         # minimum number of data points

# Number of threads
threads:
  comet: 6
  riana: 3
  fitcurve: 12